require:
  - rubocop-performance
  - rubocop-rspec

Metrics/LineLength: { Max: 100 }
Metrics/BlockLength: { Exclude: [spec/**/*] }

RSpec/BeforeAfterAll: { Enabled: false }
RSpec/ExampleLength: { Max: 20 }
RSpec/MessageSpies: { Enabled: false }
RSpec/MultipleExpectations: { Max: 5 }
RSpec/NamedSubject: { Enabled: false }

Style/Documentation: { Enabled: false }
Style/StringLiterals: { EnforcedStyle: double_quotes }
